kind: pipeline
name: default

steps:
  - name: publish
    image: python:3.7-alpine
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      MAILGUN_USER:
        from_secret: MAILGUN_USER
      MAILGUN_PASSWORD:
        from_secret: MAILGUN_PASSWORD
      CERTIFICATE_ARN:
        from_secret: CERTIFICATE_ARN
      SLS_DEBUG: "*"
    volumes:
      - name: npm
        path: /drone/src/node_modules
      - name: pip
        path: /.pip
    commands:
      - apk add --update gcc jpeg-dev musl-dev nodejs-npm zlib-dev
      - pip install --cache-dir=/.pip -r requirements.txt flake8 flake8-import-order
      - flake8
      - python manage.py test apps
      - npm install
      # - $(npm bin)/serverless deploy
      - $(npm bin)/serverless deploy function -f app
      - python manage.py collectstatic --noinput --settings=srvls.settings.production

volumes:
  - name: npm
    host:
      path: /drone/npm
  - name: pip
    host:
      path: /drone/pip

when:
  event:
    - push
  branch:
    - master
