kind: pipeline
name: default

steps:
- name: test
  image: python:3.7-alpine
  commands:
  - pip install flake8
  - flake8
  - pip install -r requirements.txt
  - python manage.py test apps
- name: publish
  image: python:3.7-alpine
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  volumes:
  - name: npm
    path: /drone/src/node_modules
  commands:
  - apk add --update nodejs-npm
  - npm install
  - $(npm bin)/serverless deploy

volumes:
- name: npm
  host:
    path: /drone/npm

when:
  event:
  - push
  branch:
  - master
