kind: pipeline
name: default

steps:
  - name: publish
    image: lambci/lambda:build-python3.7
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      MAILGUN_USER:
        from_secret: MAILGUN_USER
      MAILGUN_PASSWORD:
        from_secret: MAILGUN_PASSWORD
      CERTIFICATE_ARN:
        from_secret: CERTIFICATE_ARN

      PROJECT_NAME: srvls
      DEPLOY_STAGE: dev
      HOST_NAME: kputrajaya.com
      AWS_REGION: ap-southeast-1
      SLS_DEBUG: '*'
    volumes:
      - name: npm
        path: /drone/src/node_modules
      - name: pip
        path: /.pip
    commands:
      # Dynamic variables
      - export BUCKET_NAME=$PROJECT_NAME-$DEPLOY_STAGE
      - export CDN_DOMAIN=cdn-$PROJECT_NAME.$HOST_NAME
      - export AWS_DEFAULT_REGION=$AWS_REGION
      - export DJANGO_SETTINGS=srvls.settings.stage_$DEPLOY_STAGE

      # Testing
      - pip install --cache-dir=/.pip -r requirements.txt flake8 flake8-import-order
      - flake8
      - python manage.py test apps

      # Deployment
      - curl -sL https://rpm.nodesource.com/setup_10.x | bash -
      - yum install -y nodejs
      - npm install
      - $(npm bin)/serverless deploy -s $DEPLOY_STAGE
      # - $(npm bin)/serverless deploy function -f app -s $DEPLOY_STAGE
      - python manage.py collectstatic --noinput --settings=$DJANGO_SETTINGS

volumes:
  - name: npm
    host:
      path: /drone/npm
  - name: pip
    host:
      path: /drone/pip

when:
  event:
    - push
  branch:
    - master
