kind: pipeline
name: default

steps:
  - name: publish
    image: lambci/lambda:build-python3.8
    environment:
      # Secrets
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      MAILGUN_USER:
        from_secret: MAILGUN_USER
      MAILGUN_PASSWORD:
        from_secret: MAILGUN_PASSWORD
      CERTIFICATE_ARN:
        from_secret: CERTIFICATE_ARN

      # Configurations
      PROJECT_NAME: lorem
      HOST_NAME: kputrajaya.com
      AWS_REGION: ap-southeast-1
      DEPLOY_STAGE: dev
      SLS_DEBUG: '*'
    commands:
      # Static variables
      - export PATH=$HOME/opt/sqlite/bin:$PATH
      - export LD_LIBRARY_PATH=$HOME/opt/sqlite/lib
      - export LD_RUN_PATH=$HOME/opt/sqlite/lib

      # Dynamic variables
      - export BUCKET_NAME=$PROJECT_NAME-$DEPLOY_STAGE-app
      - export CDN_DOMAIN=$PROJECT_NAME-cdn.$HOST_NAME
      - export AWS_DEFAULT_REGION=$AWS_REGION
      - export DJANGO_SETTINGS=srvls.settings.stage_$DEPLOY_STAGE

      # Testing
      - pip install -r requirements.txt flake8 flake8-import-order
      - flake8
      - python manage.py test

      # Deployment
      - curl -sL https://rpm.nodesource.com/setup_10.x | bash -
      - yum install -y nodejs
      - npm install
      - $(npm bin)/serverless create_domain && $(npm bin)/serverless deploy -s $DEPLOY_STAGE
      # - $(npm bin)/serverless deploy function -f app -s $DEPLOY_STAGE
      - python manage.py collectstatic --noinput --settings=$DJANGO_SETTINGS
      - python manage.py migrate --settings=$DJANGO_SETTINGS

when:
  event:
    - push
  branch:
    - master
