kind: pipeline
name: default

steps:
  - name: publish
    image: python:3.7-alpine
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      SLS_DEBUG: *
    volumes:
      - name: npm
        path: /drone/src/node_modules
      - name: pip
        path: /drone/src/.pip
    commands:
      - apk add --update git nodejs-npm
      - pip install --cache-dir=.pip -r requirements.txt flake8
      - flake8
      - python manage.py test apps
      - npm install
      - $(npm bin)/serverless deploy

volumes:
  - name: npm
    host:
      path: /drone/npm
  - name: pip
    host:
      path: /drone/pip

when:
  event:
    - push
  branch:
    - master
