service: srvls

provider:
  name: aws
  runtime: python3.7
  region: ap-southeast-1
  memorySize: 256
  timeout: 10
  versionFunctions: false
  iamRoleStatements:
  - Effect: "Allow"
    Action:
    - s3:GetObject
    - s3:PutObject
    Resource: "arn:aws:s3:::*"

functions:
  app:
    handler: wsgi_handler.handler
    events:
    - http: ANY /
    - http: 'ANY {proxy+}'

plugins:
- serverless-python-requirements
- serverless-wsgi

custom:
  wsgi:
    app: srvls.wsgi.application
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
