service: ${self:custom.var.projectName}

provider:
  name: aws
  runtime: python3.7
  region: ap-southeast-1
  memorySize: 256
  timeout: 10
  versionFunctions: false
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: "arn:aws:s3:::*"

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-domain-manager
  - serverless-python-requirements
  - serverless-wsgi

custom:
  var:
    projectName: srvls
    hostName: kputrajaya.com
  customDomain:
    domainName: ${self:custom.var.projectName}.${self:custom.var.hostName}
  pythonRequirements:
    dockerizePip: non-linux
  wsgi:
    app: ${self:custom.var.projectName}.wsgi.application
    packRequirements: false

resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
            - cdn-${self:custom.var.projectName}.${self:custom.var.hostName}
          DefaultCacheBehavior:
            TargetOriginId: ${self:custom.var.projectName}
            ViewerProtocolPolicy: 'redirect-to-https'
            DefaultTTL: 2592000
            ForwardedValues:
              QueryString: false
          Enabled: true
          Origins:
            - Id: ${self:custom.var.projectName}
              DomainName: ${self:custom.customDomain.domainName}
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
          PriceClass: PriceClass_100
          ViewerCertificate:
            AcmCertificateArn: ${env:CERTIFICATE_ARN}
            MinimumProtocolVersion: TLSv1.1_2016
            SslSupportMethod: sni-only
    Route53RecordSet:
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneName: ${self:custom.var.hostName}.
        RecordSets:
        - Name: cdn-${self:custom.var.projectName}.${self:custom.var.hostName}
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt [CloudFrontDistribution, DomainName]
        - Name: cdn-${self:custom.var.projectName}.${self:custom.var.hostName}
          Type: AAAA
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt [CloudFrontDistribution, DomainName]
